module.exports = {
  important: true,
  purge: {
    content: ["./pages/**/*.tsx", "./components/**/*.tsx"],
    options: {
      safelist: {
        standard: [
          /black$/,
          /white$/,
          /pink$/,
          /blue$/,
          /green$/,
          "top-5",
          "top-30",
          "top-38",
          "top-46",
          "top-71",
          "top-79",
          "top-87",
          "h-extralarge",
          "h-extralarge_lg",
          "h-extralarge_md",
          "h-fullsection",
          "h-fullsection_md",
          "h-mediumsection",
          "h-mediumsection_md",
          "h-shortsection",
          "h-shortsection_md",
        ],
      },
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      black: "#111921",
      white: "#fffbf3",
      pink: "#f4d4d6",
      blue: "#5f8db5",
      green: "#035157",
    },
    fontFamily: {
      roboto: ["MyRoboto", "ui-sans-serif"],
      calson: ["MyCalson", "ui-serif"],
    },
    extend: {
      fontSize: {
        24: "6rem",
        28: "7rem",
        32: "8rem",
        36: "9rem",
        40: "10rem",
        44: "11rem",
        48: "12rem",
        52: "13rem",
        56: "14rem",
        60: "15rem",
      },
      width: {
        "7/20": "35%",
        "1280px": "1280px",
        "1536px": "1536px",
      },
      height: {
        "65vh": "65vh",
        entire: "700vh",
        128: "32rem",
        184: "46rem",
        extralarge: "58rem",
        extralarge_lg: "54rem",
        extralarge_md: "46rem",
        fullsection: "46rem",
        fullsection_md: "32rem",
        mediumsection: "28rem",
        mediumsection_md: "20rem",
        shortsection: "20rem",
        shortsection_md: "16rem",
      },
      margin: {
        "8vh": "8vh",
      },
      inset: {
        "1/5": "20%",
        "8p": "8%",
        "16p": "16%",
        30: "7.5rem",
        38: "9.5rem",
        46: "11.5rem",
        71: "17.75rem",
        79: "19.75rem",
        87: "21.75rem",
      },
      gridTemplateRows: {
        10: "repeat(10, minmax(0, 1fr))",
      },
      gridAutoRows: {
        fullsection: "46rem",
        fullsection_md: "32rem",
        mediumsection: "28rem",
        mediumsection_md: "20rem",
        shortsection: "20rem",
        shortsection_md: "16rem",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
