image: rockylinux/8
packages:
  - python3
  - python3-pip
secrets:
  - c6787d79-3d59-4013-9488-52c03d64c105
triggers:
  - action: email
    condition: failure
    to: Haowen Liu <lhw@lunacd.com>
tasks:
  - setup: |
      sudo dnf module -y install nodejs:16
      sudo dnf install -y nodejs
      sudo corepack enable
      sudo pip3 install -q awscli
  - fetch_assets: |
      set +x
      source ~/.berly_aws_key
      set -x
      aws s3 sync s3://berlyd-assets/public public
  - deploy: |
      set +x
      source ~/.berly_aws_key
      set -x
      cd berlyd-portfolio
      yarn
      yarn next build
      yarn next export
      aws s3 sync out s3://berlyd-website
