image: rockylinux/9
packages:
  - python3
  - python3-pip
  - nodejs
secrets:
  - c6787d79-3d59-4013-9488-52c03d64c105
triggers:
  - action: email
    condition: failure
    to: Haowen Liu <lhw@lunacd.com>
tasks:
  - setup: |
      sudo npm i -g corepack
      sudo pip3 install -q awscli
  - fetch_assets: |
      set +x
      source ~/.berly_aws_key
      set -x
      aws s3 sync s3://berlyd-assets/public public
  - deploy: |
      set +x
      source ~/.berly_aws_key
      set -x
      cd berlyd-portfolio
      yarn
      yarn export
      aws s3 sync out s3://berlyd-website
